name: 'instagram_influencer'
channels:
    - conda-forge
    - defaults
dependencies:
    -  r-base=4.1.2
    - r-shiny
    - r-plotly
    - r-dplyr
    - r-readr
    - r-tidyverse
    - r-ggplot2
    - r-data.table
    - r-jsonlite
    - r-httr